language: c
sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gnat
script:
  - ./configure
  - make
  - cd testsuite; gnatmake get_entities
  - pwd
  - cd testsuite; GHDL=$PWD/../ghdl_mcode ./testsuite
